import React, { useState } from 'react';
import { FileText, Download, Send, DollarSign, Clock, Users, CheckCircle } from 'lucide-react';
import './ProposalBuilder.css';

const ProposalBuilder = () => {
  const [proposal, setProposal] = useState({
    cliente: '',
    projeto: '',
    escopo: '',
    prazo: '',
    valor: '',
    formaPagamento: '',
    validade: ''
  });

  const generateProposal = () => {
    const date = new Date().toLocaleDateString('pt-BR');
    const validadeDate = new Date();
    validadeDate.setDate(validadeDate.getDate() + (parseInt(proposal.validade) || 7));
    
    const html = `
<!DOCTYPE html>
<html>
<head>
  <title>Proposta Comercial - ${proposal.cliente}</title>
  <style>
    body { font-family: 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #333; }
    h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
    .section { margin: 30px 0; }
    .label { font-weight: bold; color: #666; font-size: 12px; text-transform: uppercase; }
    .value { font-size: 16px; margin-top: 4px; }
    .escopo { background: #f5f5f5; padding: 20px; border-radius: 8px; white-space: pre-line; }
    .valor { font-size: 32px; color: #2563eb; font-weight: bold; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }
  </style>
</head>
<body>
  <h1>Proposta Comercial</h1>
  
  <div class="section">
    <div class="label">Cliente</div>
    <div class="value">${proposal.cliente || '________________'}</div>
  </div>
  
  <div class="section">
    <div class="label">Projeto</div>
    <div class="value">${proposal.projeto || '________________'}</div>
  </div>
  
  <div class="section">
    <div class="label">Escopo do Projeto</div>
    <div class="escopo">${proposal.escopo || 'A ser definido...'}</div>
  </div>
  
  <div class="section">
    <div class="label">Prazo de Entrega</div>
    <div class="value">${proposal.prazo || '___'} dias úteis</div>
  </div>
  
  <div class="section">
    <div class="label">Valor Total</div>
    <div class="valor">R$ ${proposal.valor || '0,00'}</div>
  </div>
  
  <div class="section">
    <div class="label">Forma de Pagamento</div>
    <div class="value">${proposal.formaPagamento || 'A combinar'}</div>
  </div>
  
  <div class="footer">
    <p>Proposta válida até ${validadeDate.toLocaleDateString('pt-BR')}</p>
    <p>Generated by CPS - Create Portfolio Studio</p>
  </div>
</body>
</html>
    `;
    
    const win = window.open('', '_blank');
    win.document.write(html);
    win.document.close();
    win.print();
  };

  return (
    <div className="proposal-builder">
      <h3><FileText size={18} /> Construtor de Propostas</h3>
      
      <div className="form-grid">
        <div className="form-field">
          <label>Cliente *</label>
          <input type="text" placeholder="Nome do cliente" 
            value={proposal.cliente} onChange={(e) => setProposal({...proposal, cliente: e.target.value})} />
        </div>
        
        <div className="form-field">
          <label>Projeto *</label>
          <input type="text" placeholder="Nome do projeto"
            value={proposal.projeto} onChange={(e) => setProposal({...proposal, projeto: e.target.value})} />
        </div>
        
        <div className="form-field full">
          <label>Escopo</label>
          <textarea placeholder="Descreva o escopo do projeto..."
            value={proposal.escopo} onChange={(e) => setProposal({...proposal, escopo: e.target.value})} rows={4} />
        </div>
        
        <div className="form-field">
          <label><Clock size={14} /> Prazo (dias)</label>
          <input type="number" placeholder="30"
            value={proposal.prazo} onChange={(e) => setProposal({...proposal, prazo: e.target.value})} />
        </div>
        
        <div className="form-field">
          <label><DollarSign size={14} /> Valor (R$)</label>
          <input type="text" placeholder="5.000,00"
            value={proposal.valor} onChange={(e) => setProposal({...proposal, valor: e.target.value})} />
        </div>
        
        <div className="form-field">
          <label>Forma de Pagamento</label>
          <select value={proposal.formaPagamento} onChange={(e) => setProposal({...proposal, formaPagamento: e.target.value})}>
            <option value="">Selecione...</option>
            <option value="50% antecipado, 50% entrega">50% antecipado, 50% entrega</option>
            <option value="Parcelado em 3x">Parcelado em 3x</option>
            <option value="Parcelado em 5x">Parcelado em 5x</option>
            <option value="Pagamento único">Pagamento único</option>
          </select>
        </div>
        
        <div className="form-field">
          <label>Validade (dias)</label>
          <input type="number" placeholder="7" defaultValue={7}
            value={proposal.validade} onChange={(e) => setProposal({...proposal, validade: e.target.value})} />
        </div>
      </div>

      <button className="generate-btn" onClick={generateProposal}>
        <Download size={16} />
        Gerar Proposta PDF
      </button>
    </div>
  );
};

export default ProposalBuilder;